Add AMQP extension
urbitassociates/docker-images pull request #34
Opened 2016-11-09 14:16 UTC by SimonForsman

Replace openssl with libressl

2016-11-09 14:30 UTC, mandrean requested changes

2016-11-09 14:30 UTC, mandrean commented on lumen-php-fpm/Dockerfile
> +RUN apk --no-cache --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ add rabbitmq-c rabbitmq-c-dev libressl libress
Split these dependencies up on separate lines using `\` (see other images)

Also, we probably shouldn't use `testing` if possible. Check if packages are available in `community`

2016-11-11 09:10 UTC, SimonForsman commented
Restructured dependency installations, testing is required for rabbitmq-c(Which is required by the php amqp extension) at the moment atleast.

2016-11-11 09:13 UTC, mandrean approved these changes

2016-11-11 09:13 UTC, merged